export const SERVER_SNAPSHOT_RECEIVED = "SERVER_SNAPSHOT_RECEIVED"
export const AUTH_TOKEN_RECEIVED = "AUTH_TOKEN_RECEIVED"
export const USER_URI_RECEIVED = "USER_URI_RECEIVED"
export const LOGOUT_REQUEST_INITIATED = "LOGOUT_REQUEST_INITIATED"
export const LOGOUT_REQUEST_DONE = "LOGOUT_REQUEST_DONE"
export const RESPONSE_STATUS_RECEIVED = "RESPONSE_STATUS_RECEIVED"

export const ALL_CHART_CONFIG_RECEIVED = "ALL_CHART_CONFIG_RECEIVED"
export const RECEIVE_CHART_CONFIG = "RECEIVE_CHART_CONFIG"
export const RECEIVE_GLOBAL_CHART_CONFIG = "RECEIVE_GLOBAL_CHART_CONFIG"
export const ALL_CHARTS_DISABLE_ANIMATION = "ALL_CHARTS_DISABLE_ANIMATION"

export const RECEIVE_CAROUSEL_CONFIG = "RECEIVE_CAROUSEL_CONFIG"

export const MARK_USER_FOR_EDIT = "MARK_USER_FOR_EDIT"
export const SERVER_USER_RECEIVED = "SERVER_USER_RECEIVED"
export const SERVER_USER_NOT_FOUND = "SERVER_USER_NOT_FOUND"

export const MARK_SETTINGS_FOR_EDIT = "MARK_SETTINGS_FOR_EDIT"
export const SERVER_SETTINGS_RECEIVED = "SERVER_SETTINGS_RECEIVED"
export const SERVER_SETTINGS_NOT_FOUND = "SERVER_SETTINGS_NOT_FOUND"

export const CURRENT_CYCLE_RECEIVED = "CURRENT_CYCLE_RECEIVED"

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const SERVER_CHANGELOG_RECEIVED = "SERVER_CHANGELOG_RECEIVED"
export const SERVER_CHANGELOG_COUNTS_COMPUTED = "SERVER_CHANGELOG_COUNTS_COMPUTED"
export const SERVER_CHANGELOG_COUNTS_VIEWED = "SERVER_CHANGELOG_COUNTS_VIEWED"

export const ADD_TO_CHART_CACHE = "ADD_TO_CHART_CACHE"
export const CHART_CACHE_RECEIVED = "CHART_CACHE_RECEIVED"

export const SERVER_PLAN_RECEIVED = "SERVER_PLAN_RECEIVED"

export const NEW_MOVEMENTS_ADDED_ACK_VALUE = "NEW_MOVEMENTS_ADDED_ACK_VALUE"

export const BODY_LIFT_WT_EXPLANATION_ACK = "BODY_LIFT_WT_EXPLANATION_ACK"
export const BODY_LIFT_WT_EXPLANATION_ACK_VALUE = "BODY_LIFT_WT_EXPLANATION_ACK_VALUE"

export const MAINTENANCE_ACK = "MAINTENANCE_ACK"
export const MAINTENANCE_ACK_VALUE = "MAINTENANCE_ACK_VALUE"

export const BODY_SEGMENT_SELECTED = "BODY_SEGMENT_SELECTED"
export const MUSCLE_GROUP_SELECTED = "MUSCLE_GROUP_SELECTED"
export const MOVEMENT_SELECTED = "MOVEMENT_SELECTED"
export const MOVEMENT_VARIANT_SELECTED = "MOVEMENT_VARIANT_SELECTED"
export const CARDIO_TYPE_SELECTED = "CARDIO_TYPE_SELECTED"
export const BML_TYPE_SELECTED = "BML_TYPE_SELECTED"

export const MARK_SET_FOR_EDIT = "MARK_SET_FOR_EDIT"
export const SERVER_SET_RECEIVED = "SERVER_SET_RECEIVED"
export const NEW_SET_SAVED_SUCCESSFULLY = "NEW_SET_SAVED_SUCCESSFULLY"
export const SERVER_SET_DELETED_ACK_RECEIVED = "SERVER_SET_DELETED_ACK_RECEIVED"
export const SERVER_SET_LOCATION_RECEIVED = "SERVER_SET_LOCATION_RECEIVED"
export const SERVER_SET_MEDIATYPE_RECEIVED = "SERVER_SET_MEDIATYPE_RECEIVED"
export const SERVER_SET_NOT_FOUND = "SERVER_SET_NOT_FOUND"

export const MARK_BODY_JOURNAL_LOG_FOR_EDIT = "MARK_BODY_JOURNAL_LOG_FOR_EDIT"
export const SERVER_BODY_JOURNAL_LOG_RECEIVED = "SERVER_BODY_JOURNAL_LOG_RECEIVED"
export const SERVER_BODY_JOURNAL_LOG_DELETED_ACK_RECEIVED = "SERVER_BODY_JOURNAL_LOG_DELETED_ACK_RECEIVED"
export const SERVER_BODY_JOURNAL_LOG_LOCATION_RECEIVED = "SERVER_BODY_JOURNAL_LOG_LOCATION_RECEIVED"
export const SERVER_BODY_JOURNAL_LOG_MEDIATYPE_RECEIVED = "SERVER_BODY_JOURNAL_LOG_MEDIATYPE_RECEIVED"
export const SERVER_BODY_JOURNAL_LOG_NOT_FOUND = "SERVER_BODY_JOURNAL_LOG_NOT_FOUND"

export const API_REQUEST_INITIATED = "API_REQUEST_INITIATED"
export const API_REQUEST_DONE = "API_REQUEST_DONE"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const CONFLICT_DETECTED = "CONFLICT_DETECTED"
export const CONFLICT_DETECTED_USER_ACK = "CONFLICT_DETECTED_USER_ACK"
export const ACCOUNT_VERIFICATION_EMAIL_SENT = "ACCOUNT_VERIFICATION_EMAIL_SENT"
export const ACCOUNT_VERIFICATION_EMAIL_SENT_USER_ACK = "ACCOUNT_VERIFICATION_EMAIL_SENT_USER_ACK"
export const FILE_IMPORT_SUCCESS = "FILE_IMPORT_SUCCESS"
export const FILE_IMPORT_SUCCESS_USER_ACK = "FILE_IMPORT_SUCCESS_USER_ACK"
export const FILE_IMPORT_ERROR = "FILE_IMPORT_ERROR"
export const FILE_IMPORT_ERROR_USER_ACK = "FILE_IMPORT_ERROR_USER_ACK"
export const PAYMENT_TOKEN_RECEIVED = "PAYMENT_TOKEN_RECEIVED"
export const PAYMENT_TOKEN_SAVED = "PAYMENT_TOKEN_SAVED"
export const PAYMENT_TOKEN_SAVED_USER_ACK = "PAYMENT_TOKEN_SAVED_USER_ACK"
export const PAYMENT_TOKEN_SAVE_ERROR = "PAYMENT_TOKEN_SAVE_ERROR"
export const PAYMENT_TOKEN_SAVE_ERROR_USER_ACK = "PAYMENT_TOKEN_SAVE_ERROR_USER_ACK"
export const USER_ACCOUNT_SUBMIT_FAILED_RESET = "USER_ACCOUNT_SUBMIT_FAILED_RESET"
export const SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
export const SUBSCRIPTION_CANCELLED_USER_ACK = "SUBSCRIPTION_CANCELLED_USER_ACK"
export const SUBSCRIPTION_CANCELLED_ERROR = "SUBSCRIPTION_CANCELLED_ERROR"
export const SUBSCRIPTION_CANCELLED_ERROR_USER_ACK = "SUBSCRIPTION_CANCELLED_ERROR_USER_ACK"
export const PASSWORD_PROMPTED_AND_SUCCESS_FOR_DANGEROUS_ACTION = "PASSWORD_PROMPTED_AND_SUCCESS_FOR_DANGEROUS_ACTION"
export const PASSWORD_PROMPTED_AND_SUCCESS_FOR_DANGEROUS_ACTION_VALUE_RECEIVED = "PASSWORD_PROMPTED_AND_SUCCESS_FOR_DANGEROUS_ACTION_VALUE_RECEIVED"

export const BANNER_REMIND_LATER = "BANNER_REMIND_LATER"

export const BECAME_UNAUTHENTICATED = "BECAME_UNAUTHENTICATED"
export const BECAME_REAUTHENTICATED = "BECAME_REAUTHENTICATED"
export const PRESENTED_LIGHT_LOGIN_FORM = "PRESENTED_LIGHT_LOGIN_FORM"
export const PASSWORD_RESET_EMAIL_SENT = "PASSWORD_RESET_EMAIL_SENT"

export const CANCEL_RECORD_EDIT = "CANCEL_RECORD_EDIT"

export const MUSCLE_GROUP_EXPANDED = "MUSCLE_GROUP_EXPANDED"
