import React from "react"
import { Link } from "react-router"
import * as urls from "../urls"

export default class PrivacyContent extends React.Component {
    render() {
        let email
        if (this.props.enableLinks) {
            email = (<a href="mailto:privacy@rikerapp.com">privacy@rikerapp.com</a>)
        } else {
            email = (<strong>privacy@rikerapp.com</strong>)
        }
        return (
            <div>
                <h1 className="page-heading">Riker Privacy Policy</h1>
                <h2>WHO WE ARE AND WHAT THIS IS</h2>
                <p>Riker (collectively referred to here as the/our "Software" or the/our "Services"), which are web and mobile based applications that help people track their strength training.</p>
                <p>We take the private nature of your personal information very seriously, and are committed to protecting it. To do that, we've set up procedures to ensure that your information is handled responsibly and in accordance with applicable data protection and privacy laws. We're grateful for your trust, and we'll act that way.</p>
                <p>This privacy policy describes what information we collect when you visit our Services, how we use that information, and what choices we offer you to access, update, and control it. This version of the policy is effective as of the latest date indicated in the Change Log, below.</p>
                <h2>TYPES OF INFORMATION</h2>
                <p>"Personal information" is any information that we could use to identify an individual. It does not include personal information that is encoded or anonymized, or publicly available information that has not been combined with non-public information.</p>
                <p>"Sensitive personal information" is information that meets the "personal information" criteria and also a.) reveals race, ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, or b.) concerns health or sex life, information about Social Security benefits, or information on criminal or administrative proceedings other than in the context of pending legal proceedings.</p>
                <h2>HOW WE COLLECT INFORMATION</h2>
                <p>We collect information two ways: Information we get from your use of our Services, and information you provide to us directly.</p>
                <p>Information we get from your use of the Services is primarily non-personally-identifying information of the sort that web browsers, servers, and services like Google Analytics* typically make available, such as the browser type, language preference, referring site, and the time of each visit. Other non-identifying information that we might have access to includes how you use the Service (e.g. search queries), your approximate location, cookies, etc.</p>
                <p>We collect this non-personally-identifying information in order to better understand how visitors use the Services and, where possible, to improve their experience. For instance, we log the time it takes to run database queries so that we can improve performance. In some cases, we may publicly display information that is not personally identifying in the aggregate, (e.g., by publishing a report on trends in the usage of our Services) or may provide the aggregate data to third parties.</p>
                <p>When you use the Services, we also collect potentially personally identifying information in the form of Internet Protocol (IP) addresses, the Uniform Resource Locator (URL) accessed, and the unique identification number associated with the account. We don't use that information to identify you, with one exception: we may discover, by reviewing log files, that a particular account is using the Services in a way that is degrading the experience for all the Services’ users. If this is discovered, we may look up personally identifiable information associated with that account in order to contact the account owner. We handle and disclose this information in the same way we handle other potentially personally identifying information as described below.</p>
                <p>Information you provide to us directly. Certain visitors to our Services choose to interact with them in ways that may require them to provide us with personally identifying information. The amount and type of information that is provided depends on the nature of the interaction. For example, we ask visitors who sign up for our Services to provide a real name, username, and email address. Organizations and individuals who engage in financial transactions to purchase paid services are asked to provide additional information, such as the personal and financial information required to process those transactions. In each case, we only collect as much information as is necessary or appropriate given the type of interaction. We do not disclose personally identifying information other than as described below. And you can always refuse to supply personally identifying information, with the caveat that it may prevent you from engaging in certain activities.</p>
                <p>If you send us a request, such as emailing us for support, we reserve the right to publish it (absent any personally identifying information) in order to help us clarify or respond to your request or help other users.</p>
                <p>In the process of supporting our Services, we may discover personally identifiable information associated with your account. The only personally identifiable information we may discover during the support process without your consent includes your email address and the names of any organizations to which you belong. Any further information will not be discovered without your consent.</p>
                <p>In the process of supporting our Services, we may need to investigate the data within your account, including data you have entered.  If this occurs, we will always request your explicit permission before looking at the data in your account.</p>
                <p>A cookie is a small piece of data that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. We use cookies to help us track visitors' use of the Services and their preferences. If you do not wish to have cookies placed on your computer, you should set your browser to refuse cookies, but should be aware that certain features of our Services may not function properly without them.</p>
                <p>If you are outside the United States, you should know that any personally identifiable information you enter into the Services will be transferred out of your country and into the United States, and possibly to other countries. By using the Services, you consent to such transfer and are representing that you have the right to transfer such information outside your country.</p>
                <p>We do not collect any personally identifiable information from children under the age of 13. If you believe that a child has provided us with personally identifiable information without the consent of his or her parent or guardian, please contact us at {email}.  If we become aware that a child under age 13 has provided us with personally identifiable information, we'll delete it.</p>
                <h2>HOW WE USE INFORMATION WE COLLECT</h2>
                <p>Notice — Notice is what this privacy policy that you're reading is all about. You are reading it, right? It's important! When we collect your personal information, we'll tell you how we're using it, any types of third parties to which we might disclose it, (other than "agents," such as vendors or contractors, who are only processing such information for us or at our direction), and the choices we offer you to limit the use of your information.</p>
                <p>Notice will be provided in clear and conspicuous language when you are first asked to provide us with personal information, or as soon as practicable thereafter, and we'll notify you before we use the information for something other than the purpose for which it was originally collected. If anything in this policy seems unclear, please don't hesitate to contact us at {email}, so we can address your question and possibly clarify this document.</p>
                <p>Although most changes are likely to be minor, we may occasionally need to change this policy. If we do update it, we'll notify you either by posting the new policy on our Services, their blogs, or by emailing you the changes or a link to the modified document. (See the "Choice" section below for information about how we'll notify you if we change our policy regarding sensitive information.) In any case, the way we use information you provide will be covered by the privacy policy that was in effect at the time it was collected.</p>
                <p>Here are some of the ways we may use personal information you provide us:</p>
                <ul>
                    <li>To allow you to register for our Services and to administer and process the registration</li>
                    <li>To communicate with you about our products, services and related issues</li>
                    <li>To evaluate the quality of our products and services, and to enhance your experience on our web sites</li>
                    <li>To maintain and administer our web sites and comply with our legal or internal obligations and policies</li>
                    <li>To transfer information to others as described in this policy or to satisfy our legal, regulatory, compliance, or auditing requirements</li>
                    <li>To charge you any fees and provide you with a receipt or resolve billing issues associated with your account</li>
                    <li>In the case of accounts created using business email domains, to provide your contact information to an administrator of the business email domain to facilitate the provision of additional products and/or services</li>
                </ul>
                <p><strong>Choice</strong> — Choice is all about making sure you have the ability to control how we share your personal information with others. We never share any of your personal information with non-agent third parties.</p>
                <p>We won't share your personal information with non-agent third parties unless we are required to do so by law, or if we believe in good faith that disclosure is reasonably necessary to protect our property, rights or those of third parties or the public at large. It is possible that we may, on occasion, buy or sell assets from or to other companies. If that should occur, user information is typically one of the assets that get transferred. Similarly, if Riker or most of its assets were acquired, or in the unlikely event that we go out of business or enter bankruptcy, user information could be transferred or acquired. You should be aware that such events can occur, and that if it does, the buyer may continue to use your personal and non-personal information, but only as set forth in this policy. Other than in these rare circumstances, Riker will not rent or sell potentially personally identifying information to anyone.</p>
                <p>We may from time to time request some of your financial information for the purposes of completing transactions you have initiated through the Services, enrolling you in discount, rebate, and other programs in which you elect to participate, protecting against or identify possible fraudulent transactions, and otherwise as needed to manage our business.</p>
                <p>If you are a registered user of our Services and have supplied your email address, we may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with the Services. We generally use our Services to communicate this type of information, so we expect to keep this type of communication to a minimum. If we do send you information that you did not expressly request, we will provide you with a way to request that you don't get any similar notices (opt-out, unsubscribe, etc.).</p>
                <p><strong>Security</strong> — All records containing personal or financial information are considered to be our property and are afforded confidential treatment at all times. We work hard to protect against the unauthorized access, use, alteration or destruction of personal or financial information. All such electronic information is stored on restricted database servers, and is generally kept until such time as you may ask us to edit or delete it, as described below. We only disclose such information to our employees, contractors or affiliates that a) need to know that information in order to process it for us or to provide other services, and b) have agreed not to disclose it to others.</p>
                <p>All interactions with our Services use the Transport Layer Security/Secure Sockets Layer (TLS/SSL) protocol. We use a third-party, industry-accepted Payment Gateway to securely process credit card transactions.</p>
                <p><strong>Data Integrity</strong> — In addition to assuring you that we will protect your personal information, we also want to make sure that it is reliable, accurate, and up-to-date. In order to do that, we provide:</p>
                <p><strong>Access</strong> — Upon request, we will provide you with reasonable access to the personal information we collect about you. Because personal information—for example, your email address—is required to use The Services, we retain personal information as long as your account is active. You will have the opportunity to correct, update, modify or delete this information updating your information in The Services. Please note that some information may remain in our records even after you request deletion of your information as permitted by the Safe Harbor Principles. Additionally, there may be limits to the amount of information we can practically provide. For example, we may limit an individual's access to personal information where the burden or expense of providing access would be disproportionate to the risks to the individual's privacy or where doing so would violate others' rights.</p>
                <p><strong>Enforcement</strong> — We will conduct internal audits of our compliance with this privacy policy, including an annual self-assessment. Our employees take your privacy as seriously as we do, and we will take all reasonable measures against any employee found to be in violation of this policy.</p>
                <p>If you have any concerns or complaints about how you think we've handled your personal information, please contact {email} or our Data Protection Officer at the address below. We will work hard to investigate and resolve any complaints you might have.</p>
                <h2>RIKER AND INFORMATION COLLECTED FROM CHILDREN</h2>
                <p>Riker does not knowingly collect personal information from children without parental consent. If we learn that we have inadvertently obtained information in violation of applicable laws, we will promptly delete the information. For more information on Riker's approach to children's use of Riker (including our compliance with the U.S. Children's Online Privacy Protection Act ("COPPA"), please see the section of our <Link to={this.props.tosUri}>Terms of Service</Link> called "Kids Under 13 and Riker."</p>
                <h2>HOW TO CONTACT US</h2>
                <p>If you have any questions about this policy or our site in general, please contact us at {email}.</p>
                <h2>SECURITY</h2>
                <p>Please see the <Link to={this.props.securityUri}>Riker Security Policy</Link>.</p>
            </div>
        )
    }
}
